version = 1

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "python"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[transformers]]
name = "black"
enabled = true