version: '3.7'

services:
  db:
    container_name: miso-db
    image: mariadb
    restart: unless-stopped
    volumes:
      - database:/var/lib/mysql
      - ./sql/init:/docker-entrypoint-initdb.d:ro
      - ./sql/scheduled:/scripts:ro
    environment:
      - MARIADB_USER=bot
      - MARIADB_PASSWORD=botpw
      - MARIADB_DATABASE=misobot
      - MARIADB_ROOT_PASSWORD=secure-af

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    ports:
      - "9080:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  image-server:
    container_name: image-server
    build: https://github.com/joinemm/sushii-image-server.git#main
    restart: unless-stopped
    init: true
    cap_add:
      - SYS_ADMIN
    expose:
      - 3000

  bot:
    container_name: miso-bot
    build: .
    security_opt:
      - seccomp:unconfined
    command: python -O main.py
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '443:443'
    env_file:
      - .env
    environment:
      - DB_HOST=miso-db
      - IMAGE_SERVER_HOST=image-server
      - WEBSERVER_HOSTNAME=miso-bot

networks:
  default:
    driver: bridge

volumes:
  database:
  grafana-storage:
  prometheus-storage:
