version: '3.7'

services:
  bot:
    container_name: miso-bot
    build: .
    security_opt:
      - seccomp:unconfined
    command: python -O main.py dev
    network_mode: host
    ports:
      - '6969:6969'
    env_file:
      - .env
    environment:
      - DB_HOST=localhost
      - IMAGE_SERVER_HOST=localhost
      - WEBSERVER_HOSTNAME=localhost
