global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'image-server'
    static_configs:
      - targets: ['image-server:3000']
  - job_name: 'miso'
    scrape_interval: 10s
    scheme: https
    static_configs:
      - targets: ['bot']
