# SPDX-FileCopyrightText: 2023 Joonas Rautiola <joinemm@pm.me>
# SPDX-License-Identifier: MPL-2.0
# https://git.joinemm.dev/miso-bot

global:
  scrape_interval: 1m

scrape_configs:

  - job_name: 'image-server'
    static_configs:
      - targets: ['image-server:3000']

  - job_name: 'miso'
    scrape_interval: 10s
    static_configs:
      - targets: ['bot:8080']
