name: Lint
on: [ push, pull_request ]
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --line-length=88 --verbose"
          version: "~= 24.4"
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: 0.4.4
          args: "--line-length=88 --ignore=E501"
